
name: run-tests

on:
  push:
    branches: [ wip ]
  pull_request:
    branches: [ wip ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Run test suite
        run: composer test
